const Chevron = () => <span className="deck-chevron" aria-hidden="true">→</span>;

function Footer({ page }: { page: number }) { return <footer className="deck-footer"><span>VIVID / WEBMCP</span><span>0{page} / 04</span></footer>; }

function First() { return <section className="deck-screen deck-first"><div className="deck-center"><h1>data visualization</h1><div className="deck-split"><span>visual</span><span className="deck-double-arrow">↔</span><span>iterative</span></div></div><Footer page={1} /></section>; }

function Second() { return <section className="deck-screen deck-second"><div className="deck-head"><span>01</span><h1>MCP gets the first view right.</h1></div><div className="deck-sequence"><div className="deck-node filled">MCP<br /><small>data → chart</small></div><Chevron /><div className="deck-node">one-shot<br /><small>requirements known</small></div><Chevron /><div className="deck-node strike">real work<br /><small>feedback · edits</small></div></div><div className="deck-bottom-line"><span>after the first view</span><b>WebMCP keeps the work in motion.</b></div><Footer page={2} /></section>; }

function Third() { return <section className="deck-screen deck-third"><div className="deck-head"><span>02</span><h1>One agent. More than one native surface.</h1></div><div className="deck-options"><div className="deck-option"><span>OPTION A</span><div className="option-hub"><b>agent</b><i /><em>WebMCP<small>BI</small></em><i /><em>WebMCP<small>Cube semantic layer</small></em></div><p>One agent coordinates both browser-native surfaces.</p></div><div className="deck-option"><span>OPTION B</span><div className="option-loop"><em>WebMCP<small>BI</small></em><b>↔</b><em>WebMCP<small>Cube semantic layer</small></em><i>agent</i></div><p>The surfaces exchange context; the agent steers the loop.</p></div></div><div className="deck-bottom-line"><span>choose a shape</span><b>hub-and-spoke or a connected loop</b></div><Footer page={3} /></section>; }

function Fourth() { return <section className="deck-screen deck-fourth"><div className="deck-head"><span>03</span><h1>A question becomes a better report.</h1></div><div className="workflow-branch"><div className="branch-start"><div className="deck-flow-node person"><span>01</span>question</div><Chevron /><div className="deck-flow-node mcp"><span>02</span>context</div></div><div className="branch-tools"><div className="deck-flow-node semantic"><span>03</span>WebMCP<br />Cube semantic layer</div><b>↕</b><div className="deck-flow-node web"><span>04</span>WebMCP<br />BI</div></div><div className="branch-end"><Chevron /><div className="deck-flow-node agent"><span>05</span>decision</div><Chevron /><div className="deck-flow-node report"><span>06</span>answer<br />or edit</div></div></div><p className="deck-flow-caption">Context can move between the semantic layer and the report before a decision.</p><Footer page={4} /></section>; }

export function WorkflowArtifact() { const last = window.location.pathname.split('/').filter(Boolean).at(-1); const page = Number(last) || 1; const Screen = page === 2 ? Second : page === 3 ? Third : page === 4 ? Fourth : First; return <main className="webmcp-deck"><nav aria-label="Screen navigation">{[1, 2, 3, 4].map((item) => <a className={item === page ? 'active' : ''} href={`/workflow/${item}`} key={item}>{item}</a>)}</nav><Screen /></main>; }
